### ISSUE TITLE
The game launch / and close instant

### ISSUE THREAD

**Issue by JLSkyzer** [OpenCubicChunks/OptiFineDevTweaker#10]
[debug.log](https://github.com/OpenCubicChunks/OptiFineDevTweaker/files/9718421/debug.log)

**Comment by myaww1337** [comment]
Specify Minecraft JAR location with "ofdev.mcjar" environment variable
If you don't know how to do it then:

1. Come to build.gradle file in your project
2. ![Example image](https://i.imgur.com/QgJeNvX.png) Find something like this
3. Before "property" lines, insert `property "ofdev.mcjar", "Put here full path to your MC JAR"`
4. ![image](https://i.imgur.com/loWfdXU.png) Apply Gradle changes
Now try to launch your project.

**Comment by JLSkyzer** [comment]
any exemple for the full path ?

**Comment by JLSkyzer** [comment]
and i juste put the ofdev jar ? ore the ofdev and optifine mods ?

**Comment by myaww1337** [comment]
> any exemple for the full path ?

C:/...{MINECRAFT_PATH}/versions/1.12.2/1.12.2.jar

**Comment by JLSkyzer** [comment]
> and i juste put the ofdev jar ? ore the ofdev and optifine mods ?

and that ?

**Comment by myaww1337** [comment]
> > and i juste put the ofdev jar ? ore the ofdev and optifine mods ?
> 
> and that ?

Put OptifineDevTweaker, and optifine jar to mods folder inside your project
