### ISSUE TITLE
Trouble with running MCreator with Optifine

### ISSUE THREAD

**Issue by BaR1BoD** [OpenCubicChunks/OptiFineDevTweaker#13]
To run Optifine in MCreator, I put the file aa_do_not_rename_OptiFineDevTweaker-2.6.10-all.jar in the mods folder and run the game in MCreator, but it gives this error

https://pastebin.pl/view/b0958802

**Comment by Niko-sk2x** [comment]
You also need to put optifine in the mods folder together with this
