### ISSUE TITLE
Any way to use it on 1.7.10 workspace?

### ISSUE THREAD

**Issue by Safraann** [OpenCubicChunks/OptiFineDevTweaker#2]
Hi guys,
I've already used your tweaker for 1.12.2, it worked great, but what about 1.7.10? Can you tell me what classes should I modifiy to have a chance to get it working on 1.7.10? I cant really change the version of the project, I mean, its part of a big modpack, and the mod Im working on is on that same version. Thanks in advance!

**Comment by Niko-sk2x** [comment]
Done in 801c721c215b1c3291a4be64c5f7219b83f4addc
