### ISSUE TITLE
OptiFineDevTweaker doesn't load

### ISSUE THREAD

**Issue by grillo78** [OpenCubicChunks/OptiFineDevTweaker#3]
I'm on 1.16.5-36.0.0 on dev env and the game doesn't load with optifine, here is a screenshot of the run folder
![image](https://user-images.githubusercontent.com/19859573/106652311-8e7cad00-6595-11eb-86a1-3d61f872440a.png)
and here the latest.log: https://hatebin.com/mnrphotagb

**Comment by Jozufozu** [comment]
It seems the `META_INF/services` folder didn't make it into the release. I was able to get it to load by adding that manually.

**Comment by Niko-sk2x** [comment]
Fixed in https://github.com/OpenCubicChunks/OptiFineDevTweaker/commit/21043554a4e04f8ba5be4563be636d417c8f2500
