### ISSUE TITLE
[1.12.2 build 2855] Optifine Dev Tweaker crash at startup

### ISSUE THREAD

**Issue by Safraann** [OpenCubicChunks/OptiFineDevTweaker#4]
Hi,
Due to recent gradle 2x and lower version incompatibility, I've been forced to update my mod to 1.12.2 build 2855 (recommended one), but I dont know why optifine dev tweaker no longer works :/
I put optifine compiled mod and dev tweaker jars in run/mods folder but the crash happens like 2 secs after start.
Here are some logs including the crash part:
https://pastebin.com/60zCWDz8
Thanks in advance.

**Comment by Niko-sk2x** [comment]
Currently this is not compatible with FG3 because FG3 legacydev setup doesn't set the system property `net.minecraftforge.gradle.GradleStart.srg.notch-mcp`, but this mod relies on it being set when running on launchwrapper.

Further, FG3 may not even generate these mappings. I will try to find a workaround for this issue, but as it is your best approach may be to set up and equivalent (same mcp mappings version, older forge) environment with FG2 (FG2 still works for me with some tricks) and look at what GradleStart sets that property to and set it to the same value manually in your run configuration.

**Comment by anatawa12** [comment]
@Barteks2x 

There's a way to get notch-mcp mapping. By defining task like below, we can get notch-mcp srg mapping at "$buildDir/generateNotchToMcp/output.tsrg". so we can set system property with `property("net.minecraftforge.gradle.GradleStart.srg.notch-mcp", "$buildDir/generateNotchToMcp/output.tsrg")` and set `generateNotchToMcp` as a dependencies of `runClient` with `afterEvaluate { tasks.prepareRuns.dependsOn(generateNotchToMcp) }`.

```
task generateNotchToMcp(type: net.minecraftforge.gradle.mcp.task.GenerateSRG) {
    mappings project.minecraft.mappings
    srg tasks.extractSrg.output
    notch true
    format "SRG"
}
```

But still There is a problem to get minecrraft jar. By default, this plugin gets Minecraft jar from `~/.gradle/caches/minecraft/net/minecraft/minecraft/1.12.2/minecraft-1.12.2.jar`. I tried Minecraft client jar in `minecraft_repo` and joined jar at `mcp_repo` but they're not working.
which version of jar should be `ofdev.mcjar`?
(tested on windows with 
```
property("ofdev.mcjar", System.getProperty("user.home") + "/.gradle/caches/forge_gradle/minecraft_repo/" +
                    "versions/1.12.2/client.jar")
```
. 
[crash-2021-04-24_22.03.08-client.txt](https://github.com/OpenCubicChunks/OptiFineDevTweaker/files/6369641/crash-2021-04-24_22.03.08-client.txt)
)

WORKAROUND: run setup 1.12.2 development with FG2 once.

**Comment by Niko-sk2x** [comment]
@anatawa12 

> There's a way to get notch-mcp mapping. By defining task like below, we can get notch-mcp srg mapping at "$buildDir/generateNotchToMcp/output.tsrg". so we can set system property with property("net.minecraftforge.gradle.GradleStart.srg.notch-mcp", "$buildDir/generateNotchToMcp/output.tsrg") and set generateNotchToMcp as a dependencies of runClient with afterEvaluate { tasks.prepareRuns.dependsOn(generateNotchToMcp) }.


I don't like using a gradle buildscript for getting the notch-mcp mappings, as that would require extra setup for this mod to work. This is a last resort way. I should be able to get a hold of mcpconfig directly and then compute the mappings from that + srg mappings that are already available.

>  which version of jar should be ofdev.mcjar?

`ofdev.mcjar` can also point at the jar used by vanilla MC launcher. It's the unmodified, obfuscated MC jar.

> But still There is a problem to get minecrraft jar. By default, this plugin gets Minecraft jar from ~/.gradle/caches/minecraft/net/minecraft/minecraft/1.12.2/minecraft-1.12.2.jar. I tried Minecraft client jar in minecraft_repo and joined jar at mcp_repo but they're not working.

This is the code I have for it on modlauncher https://github.com/OpenCubicChunks/OptiFineDevTweaker/blob/21043554a4e04f8ba5be4563be636d417c8f2500/src/main/java/ofdev/modlauncher/OFDevTransformationService.java#L57-L73

Something similar should also work as FG3+ fallback for 1.12.2 and older.

But if you claim it doesn't work, I will have to investigate myself
