### ISSUE TITLE
crash at the launch of the game

### ISSUE THREAD

**Issue by redmine4404** [OpenCubicChunks/OptiFineDevTweaker#8]
Hello, I can't launch optifine with forge gradle 1.7.10. the logs :   https://pastebin.com/10NDL9zj

**Comment by Niko-sk2x** [comment]
The log has expired or has been deleted.

**Comment by redmine4404** [comment]
https://www.toptal.com/developers/hastebin/exotowicox.md

**Comment by redmine4404** [comment]
the logs file

**Comment by Niko-sk2x** [comment]
That looks like 1.7.10 doesn't use log4j or uses an incompatible version of it... I didn't expect that. Will be fixed soon. If 1.7.10 doesn't use log4j at all, you can try adding it as a runtime dependency as a workaround

**Comment by redmine4404** [comment]
I will try to use the most recent version of log4j compatible with java 8 (sorry for my english I am french)

**Comment by redmine4404** [comment]
actually I don't know how to do this so I will wait for the next update
